"""
Cleans and standardizes the raw source-system exports in data/raw/ into typed,
deduplicated tables in data/processed/, and writes a short data-quality report
documenting exactly what was fixed and why (outputs/data_quality_report.md).

This is the "T" (and part of the "L") in the pipeline's ELT split:
  1. python/etl_clean_transform.py  -> fixes data-quality issues (this file)
  2. python/load_warehouse.py       -> loads clean tables into DuckDB
  3. dbt (dbt/euro_ecom)            -> builds the dimensional model + marts

Run:
    python python/etl_clean_transform.py
"""
from pathlib import Path

import numpy as np
import pandas as pd

BASE = Path(__file__).resolve().parent.parent
RAW = BASE / "data" / "raw"
PROCESSED = BASE / "data" / "processed"
PROCESSED.mkdir(parents=True, exist_ok=True)

VALID_COUNTRIES = {"DE", "FR", "GB", "NL", "ES", "IT", "SE"}
CANONICAL_CATEGORIES = [
    "Electronics", "Fashion", "Home & Garden", "Beauty & Health",
    "Sports & Outdoors", "Toys & Kids", "Books & Media", "Grocery",
]
CATEGORY_LOOKUP = {c.strip().lower(): c for c in CANONICAL_CATEGORIES}

report_lines = ["# Data Quality Report\n", "Generated by `python/etl_clean_transform.py`.\n"]


def log(msg: str):
    report_lines.append(f"- {msg}")
    print(msg)


def clean_country_code(series: pd.Series) -> pd.Series:
    return series.astype(str).str.strip().str.upper()


def parse_mixed_date(series: pd.Series) -> pd.Series:
    """Handles a mix of ISO (YYYY-MM-DD), slash (DD/MM/YYYY) and dash (DD-MM-YYYY) formats."""
    iso = pd.to_datetime(series, format="%Y-%m-%d", errors="coerce")
    slash = pd.to_datetime(series, format="%d/%m/%Y", errors="coerce")
    dash = pd.to_datetime(series, format="%d-%m-%Y", errors="coerce")
    return iso.fillna(slash).fillna(dash)


def clean_customers() -> pd.DataFrame:
    df = pd.read_csv(RAW / "customers_raw.csv")
    before = len(df)
    df = df.drop_duplicates(subset="customer_id", keep="first")
    log(f"customers: dropped {before - len(df)} exact duplicate customer_id rows")

    df["first_name"] = df["first_name"].str.strip()
    df["last_name"] = df["last_name"].str.strip()
    df["country_code"] = clean_country_code(df["country_code"])
    invalid = ~df["country_code"].isin(VALID_COUNTRIES)
    if invalid.any():
        log(f"customers: {invalid.sum()} rows had an unrecognized country_code, mapped to 'UNK'")
    df.loc[invalid, "country_code"] = "UNK"

    missing_email = df["email"].isna().sum()
    log(f"customers: {missing_email} rows ({missing_email / len(df):.1%}) have a missing email (kept null, not imputed)")

    df["birth_date"] = pd.to_datetime(df["birth_date"], errors="coerce").dt.date
    df["signup_date"] = pd.to_datetime(df["signup_date"], errors="coerce").dt.date
    df["marketing_opt_in"] = df["marketing_opt_in"].astype(bool)
    return df.reset_index(drop=True)


def clean_products() -> pd.DataFrame:
    df = pd.read_csv(RAW / "products_raw.csv")
    df["category"] = df["category"].astype(str).str.strip().str.lower().map(CATEGORY_LOOKUP).fillna("Unknown")

    missing_cost = df["unit_cost_eur"].isna()
    if missing_cost.any():
        # impute missing cost using the median cost-to-price ratio observed within the same category
        ratio_by_cat = (df["unit_cost_eur"] / df["unit_price_eur"]).groupby(df["category"]).median()
        overall_ratio = (df["unit_cost_eur"] / df["unit_price_eur"]).median()
        imputed = df.loc[missing_cost, "category"].map(ratio_by_cat).fillna(overall_ratio) * df.loc[missing_cost, "unit_price_eur"]
        df.loc[missing_cost, "unit_cost_eur"] = imputed.round(2)
        log(f"products: imputed {missing_cost.sum()} missing unit_cost_eur values using median category cost ratio")

    df["launch_date"] = pd.to_datetime(df["launch_date"], errors="coerce").dt.date
    return df


def clean_orders() -> pd.DataFrame:
    df = pd.read_csv(RAW / "orders_raw.csv")
    before = len(df)
    df = df.drop_duplicates(subset="order_id", keep="first")
    log(f"orders: dropped {before - len(df)} duplicate order_id rows (retried export job)")

    mixed_format = df["order_date"].astype(str).str.contains("/")
    log(f"orders: normalized {mixed_format.sum()} order_date values from DD/MM/YYYY to ISO format")
    df["order_date"] = parse_mixed_date(df["order_date"]).dt.date

    df["country_code"] = clean_country_code(df["country_code"])
    df["currency_code"] = df["currency_code"].astype(str).str.strip().str.upper()

    negative = df["net_amount_eur"] < 0
    log(f"orders: corrected {negative.sum()} rows with a negative net_amount_eur (data-entry sign error)")
    df["data_quality_flag"] = np.where(negative, "corrected_negative_amount", None)
    df["net_amount_eur"] = df["net_amount_eur"].abs()
    df["gross_amount_eur"] = df["gross_amount_local"].abs()
    df = df.drop(columns=["gross_amount_local"])

    return df.reset_index(drop=True)


def clean_order_items() -> pd.DataFrame:
    df = pd.read_csv(RAW / "order_items_raw.csv")
    before = len(df)
    df = df.drop_duplicates()
    if before != len(df):
        log(f"order_items: dropped {before - len(df)} exact duplicate rows")
    return df


def clean_payments() -> pd.DataFrame:
    df = pd.read_csv(RAW / "payments_raw.csv")
    df["payment_method"] = df["payment_method"].astype(str).str.strip().str.lower()
    return df.drop_duplicates(subset="order_id", keep="first")


def clean_returns() -> pd.DataFrame:
    df = pd.read_csv(RAW / "returns_raw.csv")
    mixed_format = df["return_date"].astype(str).str.contains("-") & ~df["return_date"].astype(str).str.match(r"^\d{4}-")
    df["return_date"] = parse_mixed_date(df["return_date"]).dt.date
    missing_reason = df["return_reason"].isna().sum()
    log(f"returns: {missing_reason} rows had a missing return_reason, filled with 'unspecified'")
    df["return_reason"] = df["return_reason"].fillna("unspecified")
    return df


def clean_marketing_spend() -> pd.DataFrame:
    df = pd.read_csv(RAW / "marketing_spend_raw.csv")
    df["date"] = pd.to_datetime(df["date"]).dt.date
    negative = df["spend_eur"] < 0
    if negative.any():
        log(f"marketing_spend: clipped {negative.sum()} negative spend values to 0")
    df["spend_eur"] = df["spend_eur"].clip(lower=0)
    return df


def clean_exchange_rates() -> pd.DataFrame:
    df = pd.read_csv(RAW / "exchange_rates_raw.csv")
    df["date"] = pd.to_datetime(df["date"]).dt.date
    # add an explicit EUR/EUR=1.0 rate row per day so every country_code has a joinable currency rate
    eur_rows = pd.DataFrame({
        "date": sorted(df["date"].unique()),
        "currency_code": "EUR",
        "rate_to_eur": 1.0,
    })
    out = pd.concat([df, eur_rows], ignore_index=True)
    log(f"exchange_rates: added {len(eur_rows)} EUR base-currency rows (rate=1.0) for join symmetry")
    return out


def main():
    cleaners = {
        "customers": clean_customers,
        "products": clean_products,
        "orders": clean_orders,
        "order_items": clean_order_items,
        "payments": clean_payments,
        "returns": clean_returns,
        "marketing_spend": clean_marketing_spend,
        "exchange_rates": clean_exchange_rates,
    }
    for name, fn in cleaners.items():
        df = fn()
        out_path = PROCESSED / f"{name}.csv"
        df.to_csv(out_path, index=False)
        log(f"{name}: wrote {len(df):,} clean rows -> {out_path.relative_to(BASE)}")
        report_lines.append("")

    report_path = BASE / "outputs" / "data_quality_report.md"
    report_path.parent.mkdir(exist_ok=True)
    report_path.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"\nData quality report written to {report_path}")


if __name__ == "__main__":
    main()
